services:
  - type: web
    name: accessibility-checker-backend
    env: node
    region: singapore
    plan: free
    rootDir: backend
    buildCommand: npm install && npm run build
    startCommand: npm run start
    envVars:
      - key: PORT
        value: 10000
      - key: CORS_ORIGIN
        value: "*"
      - key: PLAYWRIGHT_BROWSERS_PATH
        value: "0"
